# -*- python -*-

tools = ['default', 'prefixoptions', 'netcdfcxx', 'vardb', 'raf']
env = Environment(tools=tools)

env.Append(CCFLAGS='-g -Wall')

sources = Split("""
process2d.cpp
netcdf.cpp
probe.cpp
ProbeData.cpp
""")

process2d = env.Program(target='process2d', source=sources)
env.Default(process2d)
env.InstallProgram('process2d')
