# -*- python -*-

Import('env')

tools = ['default', 'netcdf']

env.Append(LIBS = ['VarDB', 'raf', '-lnetcdf_c++', '-lnetcdf', '-lhdf5_hl', '-lhdf5'])

process2d = env.Program('process2d', ['process2d.cpp', 'netcdf.cpp', 'probe.cpp', 'ProbeData.cpp'])

Alias('install', env.Install('$BINDIR', process2d))
