# -*- python -*-

env = Environment()

env.Append(CCFLAGS='-g -Wall')

tools = ['default', 'netcdf']

env.Append(CPPPATH = ["../"])
env.Append(CPPPATH = ["../include"])
env.Append(CPPPATH = ["../vardb"])
env.Append(CPPPATH = ["../vardb/lib"])

env.Append(LIBPATH = ["../lib"])
env.Append(LIBPATH=["../vardb"])
env.Append(LIBPATH=["../vardb/lib"])

env.Append(LIBS = ['VarDB', 'raf', 'netcdf_c++', 'netcdf', 'hdf5_hl', 'hdf5'])

sources = Split("""
process2d.cpp
netcdf.cpp
probe.cpp
ProbeData.cpp
""")

process2d = env.Program(target = 'process2d', source = sources)
env.Default(process2d)

env.Install("$INSTALL_PREFIX/bin", 'process2d')
