#!python

env = Environment(tools=['default', 'raf'])

env.Append(CXXFLAGS='-g -std=c++11 -Wall')

sources = Split("""
main.cc
""")


translate2ds = env.Program(target = 'translate2ds', source = sources)
env.Default(translate2ds)

env.Install("$INSTALL_PREFIX/bin", 'translate2ds')
