#!python

Import('PREFIX')

env = Environment()

env.Append(CCFLAGS='-g -Wall')

sources = Split("""
main.cc
""")


env.Program(target = 'translate2ds', source = sources)

env.Alias('install', env.Install(PREFIX+'/bin', 'translate2ds'))
