#!/bin/bash

# Default install location to current working directory.
PREFIX=`pwd`

# Process arguments
for i in "$@"
do
case $i in
    --prefix=*)
    PREFIX="${i#*=}"
    shift # past argument
    ;;
    -h|--help)
    echo "Usage: build_all [--prefix=/path/to/install]"
    exit
    ;;
    *)
            # unknown option
    ;;
esac
done

export PREFIX
echo "Install path will be :" $PREFIX

# Make sure all the [obvious] directories exist
test -d ${PREFIX}/bin || mkdir ${PREFIX}/bin
test -d ${PREFIX}/man || mkdir ${PREFIX}/man
test -d ${PREFIX}/man/man1 || mkdir ${PREFIX}/man/man1
test -d ${PREFIX}/man/man3 || mkdir ${PREFIX}/man/man3


# Programs using 'scons' and 'scons install'.

for file in cip/pads2oap cip/padsinfo oapinfo process2d translate2ds xpms2d 
do
  (cd $file; echo $file; scons install)
done
