# -*- python -*-

env = Environment()
env.Append(CCFLAGS='-g -Wall')
env.Append(CPPPATH=["../"])

sources = Split("""
oapinfo.cc
""")

oapinfo=env.Program(target = 'oapinfo', source = sources)
env.Default(oapinfo)

env.Install("$INSTALL_PREFIX/bin", 'oapinfo')
