# -*- python -*-

env = Environment(tools = ['default', 'raf'])
env.Append(CXXFLAGS='-g -std=c++20 -Werror -Wall')

sources = Split("""
oapinfo.cc
""")

oapinfo=env.Program(target = 'oapinfo', source = sources)
env.Default(oapinfo)

env.Install("$INSTALL_PREFIX/bin", 'oapinfo')
