#!python

# This SConstruct does nothing more than load the SConscript in this dir
# The Environment() is created in the SConstruct script
# This dir can be built standalone by executing scons here, or together
# by executing scons in a parent directory

import eol_scons

def Oapinfo(env):
    env['DEFAULT_INSTALL_PREFIX']=".."
    env['DEFAULT_OPT_PREFIX']=".."

    env.Require(['default','prefixoptions'])

    # It would be *better* to include the raf tool from vardb/raf, but 
    # until I can figure out how to do that, this works.
    env.Append(CPPPATH=['$DEFAULT_OPT_PREFIX/vardb'])

env = Environment(GLOBAL_TOOLS = [Oapinfo])

SConscript('SConscript')
