# -*- python -*-

Import('PREFIX')

env = Environment()

env.Append(CCFLAGS='-g -Wall')
env.Append(CPPPATH = PREFIX)

env.Program('oapinfo.cc')

Alias('install', env.Install(PREFIX+'/bin', 'oapinfo'))
