#!python

Import('env')

try:
  import eol_scons
  print('trying sites_scons')
except:
  print('trying .. sites_scons')
  sys.path.append("../site_scons")
  import eol_scons

tools = ['default', 'openmotif']

env.Append(CPPPATH=['class'])

env.Append(CCFLAGS=['-Wno-write-strings'])

env.Append(CPPDEFINES=['-DPNG'])
if env['PLATFORM'] == 'darwin':
  env.Append(CPPDEFINES=['-DPNG15'])


env.Append(LIBS=['raf'])
env.Append(LIBS=['png'])
env.Append(LIBS=['z'])

sources = Split("""
class/CanvasWindow.cc
class/Colors.cc
class/ControlWindow.cc
class/DataFile.cc
class/Enchilada.cc
class/FileMgr.cc
class/Hex.cc
class/Histogram.cc
class/Magnify.cc
class/MagnifyCanvas.cc
class/MagnifyWindow.cc
class/MainCanvas.cc
class/Probe.cc
src/cb_canvas.cc
src/cb_control.cc
src/cb_mag.cc
src/cb_menus.cc
src/cb_printer.cc
src/cb_text.cc
src/ccb.cc
src/global.cc
src/process.cc
src/xml.cc
src/xpms2d.cc
""")


env.Program(target = 'src/xpms2d', source = sources)

env.Alias('install', env.Install('$BINDIR', 'src/xpms2d'))
