#!python

env = Environment(tools = ['default', 'openmotif'])


env.Append(CPPPATH='class')
env.Append(LIBPATH=["../lib"])

env.Append(CXXFLAGS='-Wall -Wno-write-strings')

env.Append(CPPDEFINES=['PNG'])
if env['PLATFORM'] == 'darwin':
  env.Append(CPPDEFINES=['PNG15'])


env.Append(LIBS=['raf'])
env.Append(LIBS=['png'])
env.Append(LIBS=['z'])

sources = Split("""
class/CanvasWindow.cc
class/Colors.cc
class/ControlWindow.cc
class/DataFile.cc
class/Enchilada.cc
class/FileMgr.cc
class/Hex.cc
class/Histogram.cc
class/Magnify.cc
class/MagnifyCanvas.cc
class/MagnifyWindow.cc
class/MainCanvas.cc
class/Probe.cc
src/cb_canvas.cc
src/cb_control.cc
src/cb_mag.cc
src/cb_menus.cc
src/cb_printer.cc
src/cb_text.cc
src/ccb.cc
src/global.cc
src/process.cc
src/xml.cc
src/xpms2d.cc
""")


xpms2d = env.Program(target = 'src/xpms2d', source = sources)
env.Default(xpms2d)

env.Install("$INSTALL_PREFIX/bin", 'src/xpms2d')
