# -*- python -*-

env = Environment()

env.Append(CCFLAGS='-g -Wall')

sources = Split("""
padsinfo.cc
""")

padsinfo = env.Program(target = 'padsinfo', source = sources)
env.Default(padsinfo)

env.Install("$INSTALL_PREFIX/bin", 'padsinfo')
