# -*- python -*-

env = Environment()

env.Append(CCFLAGS='-g -Wall')

sources = Split("""
pads2oap.cc
""")

pads2oap = env.Program(target = 'pads2oap', source = sources)
env.Default(pads2oap)

env.Install("$INSTALL_PREFIX/bin", 'pads2oap')
